import os

env = CoreEnvironment(LIBS=[
        ],
                      DEBUG=1)

cpp_files = env.Glob('*.cpp')
logsvc_daemon = env.SharedLibrary("#/build/logsvc_daemon", cpp_files)

Export("logsvc_daemon")
env = CoreEnvironment(DEBUG=1,
                      LIBS=[
        "boost_filesystem",
        "boost_regex",
        "boost_system",
        "boost_unit_test_framework",
        ])
Import("log")
env.Append(LIBS=log)
env.TestLibrary(logsvc_daemon)

Return("logsvc_daemon")
