
Import("network")

env = CoreEnvironment(DEBUG=1,
                      LIBS=[
        "boost_unit_test_framework",
        ])
env['CPPDEFINES'] = { 'BOOST_TEST_DYN_LINK': None }
cpp_files = env.Glob('*.cpp')
libs = [network] + env['LIBS']

test_network = env.Program("test_network", cpp_files, LIBS=libs)
installed_test = env.Install(source = test_network, dir = "#/build")
env.AddPostAction(installed_test, Action("@build/%s" % test_network[0]))

env.Alias("build", installed_test)
env.Default("build")

