import os

env = CoreEnvironment(LIBS=[
        ],
                      DEBUG=1)

cpp_files = env.Glob('*.cpp')
cpp_files += env.Glob(os.path.join("client", "*.cpp"))
logsvccpp = env.SharedLibrary("#/build/logsvccpp", cpp_files)

Export("logsvccpp")

env = CoreEnvironment(DEBUG=1,
                      LIBS=[
        "boost_filesystem",
        "boost_unit_test_framework",
        "boost_system",
        ])
Import(['log', 'network'])
env.Append(LIBS=[log, network])
env.TestLibrary(logsvccpp)

Return("logsvccpp")
