
env = CoreEnvironment(LIBS=[
        "boost_filesystem",
        "boost_system",
        ],
                      DEBUG=1,
                      PKGS=[
        ],
                      )



cpp_files = env.Glob('*.cpp')

libs = ['logsvc_daemon', 'log', 'network']
libs += env['LIBS'][:]
logsvcd = env.Program('logsvcd', cpp_files, LIBPATH='#/build', LIBS=libs)
installed_logsvcd = env.Install(dir="#/build", source=logsvcd)

env.Alias("build", installed_logsvcd)
env.Default("build")

Return("installed_logsvcd")
