
env = CoreEnvironment(LIBS=[
        "boost_filesystem",
        "boost_system",
        ],
                      DEBUG=1,
                      PKGS=[
        ],
                      )



cpp_files = env.Glob('*.cpp')

libs = ['logsvc_daemon', 'log', 'network', 'pthread']
libs += env['LIBS'][:]
logsvcd = env.Program('#/build/logsvcd', cpp_files,
                      LIBPATH='#/build', LIBS=libs)

env.Alias("build", logsvcd)
env.Default("build")

Return("logsvcd")
