import os

Import(Split("daemon libs"))

st = os.path.join("systest", "systest.py")
systestlog = Command("#/systest.log", "systest.py", "%s $TARGET" % st)

for lib in libs:
    Depends(systestlog, lib)
Depends(systestlog, "Makefile")
Depends(systestlog, daemon)

Default(systestlog)
