env = CoreEnvironment(DEBUG=1,
                      LIBS=[
        "boost_filesystem",
        "boost_unit_test_framework",
        "boost_system",
        ])
env['CPPDEFINES'] = { 'BOOST_TEST_DYN_LINK': None }
cpp_files = env.Glob('*.cpp')
libs = ["logsvccpp", "log", "network"] + env['LIBS']

test_logsvccpp = env.Program("test_logsvccpp", cpp_files, LIBS=libs,
                             LIBPATH=["#build"])
installed_test = env.Install(source = test_logsvccpp, dir = "#/build")
env['ENV']['LD_LIBRARY_PATH'] = Dir("#/build")
env.AddPostAction(installed_test, Action("@build/%s" % test_logsvccpp[0]))

env.Alias("build", installed_test)
env.Default("build")
