
Import("log")

env = CoreEnvironment(DEBUG=1,
                      LIBS=[
        "boost_unit_test_framework",
        "boost_filesystem",
        "boost_system",
        "boost_regex",
        ])
env['CPPDEFINES'] = { 'BOOST_TEST_DYN_LINK': None }
cpp_files = env.Glob('*.cpp')
libs = [log] + env['LIBS']

test_log = env.Program("test_log", cpp_files, LIBS=libs)
installed_test = env.Install(source = test_log, dir = "#/build")
run_test = env.AddPostAction(installed_test, Action("@build/%s" % test_log[0]))
env.AlwaysBuild(run_test)

env.Alias("build", installed_test)
env.Default("build")
