
Import("logsvc_daemon")

env = CoreEnvironment(DEBUG=1,
                      LIBS=[
        "boost_filesystem",
        "boost_system",
        "boost_unit_test_framework",
        ])
env['CPPDEFINES'] = { 'BOOST_TEST_DYN_LINK': None }
cpp_files = env.Glob('*.cpp')
libs = [logsvc_daemon] + env['LIBS']

test_logsvc_daemon = env.Program("test_logsvc_daemon", cpp_files, LIBS=libs)
installed_test = env.Install(source = test_logsvc_daemon, dir = "#/build")
env.AddPostAction(installed_test, Action("@build/%s" % test_logsvc_daemon[0]))

env.Alias("build", installed_test)
env.Default("build")

