import os

env = CoreEnvironment(LIBS=[
        ],
                      DEBUG=1)

cpp_files = env.Glob('*.cpp')
log = env.SharedLibrary("#/build/log", cpp_files)

Export("log")
env = CoreEnvironment(DEBUG=1,
                      LIBS=[
        "boost_unit_test_framework",
        "boost_filesystem",
        "boost_system",
        "boost_regex",
        ])
env.TestLibrary(log)

Return("log")
