import os

libs = []
for library in [
    "network",
    "log",
    "logsvccpp",
    "logsvc_daemon",
    ]:
    path_to_SConscript = os.path.join(library, "SConscript")
    if os.path.exists(path_to_SConscript):
        libs.extend(SConscript(path_to_SConscript))
    else:
        print("warning: Missing SConscript file in folder: %s" % library)

Export("libs")

daemon = SConscript(os.path.join("logsvc_daemon_main", "SConscript"))
Export("daemon")

SConscript(os.path.join("systest", "SConscript"))
# SConscript(os.path.join("logsvcc", "SConscript"))
# SConscript(os.path.join("logsvcpy", "SConscript"))
# SConscript(os.path.join("logsvcj", "SConscript"))
