import os

env = CoreEnvironment(LIBS=[
        ],
                      DEBUG=1)

cpp_files = env.Glob('*.cpp')
network = env.SharedLibrary("#/build/network", cpp_files)

Export("network")
env = CoreEnvironment(DEBUG=1,
                      LIBS=[
        "boost_unit_test_framework",
        ])
env.TestLibrary(network)

Return("network")
